### ISSUE TITLE
Images are repeated within ```ssl-transfer/caltech101-splits/train.txt``` file.

### ISSUE THREAD

**Issue by shyammarjit** [linusericsson/ssl-transfer#10]
Images are repeated within ```ssl-transfer/caltech101-splits/train.txt```  file. For example: [example-1](https://github.com/linusericsson/ssl-transfer/blob/97411c844553549c62ce261ef3cc0747441cae2a/caltech101-splits/train.txt#L1845C1-L1846C24), [example-2](https://github.com/linusericsson/ssl-transfer/blob/97411c844553549c62ce261ef3cc0747441cae2a/caltech101-splits/train.txt#L9C1-L10C35), [example-3](https://github.com/linusericsson/ssl-transfer/blob/97411c844553549c62ce261ef3cc0747441cae2a/caltech101-splits/train.txt#L7C1-L8C35) and there are many more. Total unique element in the txt file is ```2416``` instead of ```3060```.

**Comment by linusericsson** [comment]
Thank you for spotting this! It's been fixed now and there are 2416 elements.
