### ISSUE TITLE
Best Hyperparameters

### ISSUE THREAD

**Issue by AhmadM-DL** [linusericsson/ssl-transfer#2]
Hello,
I just wonder where I can find the best hyperparameters  "C" according to your experiments.
For different datasets I mean.
Regards,

**Comment by linusericsson** [comment]
Hi Ahmad,

I've now updated the repo with a script  `run_linear.sh` that contains all the hyperparameters for reproducing the linear evaluation in the paper.

Best wishes,
Linus
