### ISSUE TITLE
Data download?

### ISSUE THREAD

**Issue by Wangt-CN** [linusericsson/ssl-transfer#4]
Hi, thanks for your great work. I want to ask that how can I quickly downloader all the data (cars, flowers, SUN and so on).　Would you have any scripts? Thanks a lot for your help.

**Comment by linusericsson** [comment]
Hi,
Unfortunately, I don't have a simple script that automates it, but these are the web pages where the datasets can be downloaded from:

Aircraft - https://www.robots.ox.ac.uk/~vgg/data/fgvc-aircraft/
Caltech101 - http://www.vision.caltech.edu/Image_Datasets/Caltech101/
Cars - https://ai.stanford.edu/~jkrause/cars/car_dataset.html
CIFAR10/100 - from torchvision
DTD - https://www.robots.ox.ac.uk/~vgg/data/dtd/
Flowers - https://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html
Food - https://data.vision.ee.ethz.ch/cvl/datasets_extra/food-101/
Pets - https://www.robots.ox.ac.uk/~vgg/data/pets/
SUN397 - https://vision.princeton.edu/projects/2010/SUN/
VOC - http://host.robots.ox.ac.uk/pascal/VOC/

It should be easy to download the files from these, just note that for some datasets you'll need to download the splits/devkits as well.

**Comment by Wangt-CN** [comment]
Very appreciate~
