### ISSUE TITLE
Encoder model for Semantic-Segmentation

### ISSUE THREAD

**Issue by anshulbshah** [linusericsson/ssl-transfer#7]
Hello!

Thanks for the great repo! 
I had some trouble in using models for semantic-segmentation. It seems like the MIT-Seg repo has a custom resnet model. I get the following error when I try to run `python train.py --gpus 0,1 --cfg selfsupconfig/moco-v2.yaml` : 

```
Loading weights for net_encoder
Traceback (most recent call last):
  File "train.py", line 273, in <module>
    main(cfg, gpus)
  File "train.py", line 144, in main
    net_encoder = ModelBuilder.build_encoder(
  File "/cis/home/ashah/Code/ssl-transfer/semantic-segmentation/mit_semseg/models/models.py", line 108, in build_encoder
    net_encoder.load_state_dict(
  File "/cis/home/ashah/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resnet:
        size mismatch for conv1.weight: copying a param with shape torch.Size([64, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).
        size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
        size mismatch for layer1.0.downsample.0.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).

```
Is this expected ? Did you skip loading weights for these layers when finetuning ? 
Thanks!

**Comment by nuistji** [comment]
I got the same problem, have you solved it? @anshulbshah

**Comment by nuistji** [comment]
I have used the weights_encoders (**.pth file) which is used for classification tasks, some keys in the '**.pth' file is removed.  We should use the original '**.pth' files.

**Comment by nuistji** [comment]
I have used the weights_encoders (*.pth file) which is used for classification tasks, some keys in the '*.pth' file is removed. We should use the **original** '*.pth' files.

**Comment by daofeng2007** [comment]
Did you solve the problem?

**Comment by nuistji** [comment]
I used the checkpoint file which is downloaded from the url link directly. Since I met the problem because I have loaded the checkpoint files which are handled by the many/few shots tasks (these tasks changed the keys of the original files.)


| |
季繁繁
|
|


|
签名由网易邮箱大师定制
On 1/12/2022 07:12，Tao ***@***.***> wrote：

Did you solve the problem?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anshulbshah** [comment]
Unfortunately, I haven't solved the problem and did not get a chance to debug this further.

**Comment by vtddggg** [comment]
we also met the same problem

```
RuntimeError: Error(s) in loading state_dict for Resnet:
	size mismatch for conv1.weight: copying a param with shape torch.Size([64, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3]).
	size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 128, 1, 1]).
	size mismatch for layer1.0.downsample.0.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 1]).
```

**Comment by vtddggg** [comment]
@linusericsson Can you give some advice ?

**Comment by vtddggg** [comment]
@linusericsson Do we need to modify the customized resnet50 in ADE20K Semantic-Segmentation to match the standard resnet50 in torchvision ?

**Comment by linusericsson** [comment]
Hi, sorry for the delay.

Yes, I believe you will need to match up the resnet50 architecture to match the pre-trained weights that are provided.
All the provided pre-trained weights use the torchvision specification of the architecture.
